### PR TITLE
Replaces Poison with Jason

### PR DESCRIPTION
**Pull request by gottfrois**
Based on https://github.com/Aircloak/phoenix_gen_socket_client/pull/40/files minus the noise around fixing various warnings.

### CODE REVIEW

**Comment by gottfrois** [comment]
@xadhoom feedback welcome mate ;)

**Comment by gottfrois** [comment]
@xadhoom hey mate, any chance to merge this PR anytime soon? :)

**Comment by xadhoom** [comment]
hey @gottfrois I'm not the maintainer, I think @sasa1977 should be pinged ;)

**Comment by sasa1977** [comment]
Since I'm not with Aircloak anymore, I don't maintain this either, i.e. I don't have any permissions to merge . Let's ping @sebastian and see if he can help :-)

**Comment by sebastian** [comment]
Sorry for letting this pull-request hang for so long @gottfrois! Somehow I didn't have notifications turned on for this repo!

I'll take a look when back at the office next week.

**Comment by gottfrois** [comment]
@xadhoom ah sorry about that mate! 🤣 
@sebastian sounds great!

**Comment by sebastian** [comment]
Thank you for the pull-request @gottfrois.

**Comment by sebastian** [comment]
Thank you again for this pull-request.
I have published a new version containing your changes.

**Pull request merged**
