### PR TITLE
Expose a push/3 that does not explicitly depend on a transport

### PR DESCRIPTION
**Pull request by gregwoodward**
Hi:
We created a push/3 function that doesn't require a transport so that we can push items to the channel from other modules. Can you take a look at this, and potentially merge it into your version?

Thanks so much,
Greg

### CODE REVIEW

**Comment by sasa1977** [comment]
Thank you for this PR!

Unfortunately, I don't think we can accept it in this shape. The main problem is that you now require that the socket client process is a named singleton, which means that we can have at most one socket connection in the entire system, which is definitely not a good general solution. 

Another issue is that `push/3` is async (cast). If we're adding this support, we'd also need to support the sync version based on a call, which would return `:ok` or `:error`, indicating whether the message has been pushed to the socket. In fact, if this was available, I'd most often use the sync version. Another question is: do we then need a "total sync" version, which returns only when the client has responded. As you can see this can get complicated pretty quickly.

On the other hand, implementing an async push from another process is already fairly trivial:

```elixir
defmodule YourSocket do
  def push(socket, event, payload), do:
    send(socket, {:push, event, payload})

  # ...

  def handle_info({:push, event, payload}, transport, state) do
    GenSocketClient.push(transport, topic, event, payload)
    {:ok, state}
  end
end
```

And now you can invoke `YourSocket.push(socket, event, payload)` from an arbitrary process.

If you want to name your socket process, it's as easy as:

```elixir
defmodule YourSocket do
  @behaviour GenSocketClient

  def start_link(...), do:
    GenSocketClient.start_link(..., name: __MODULE__)

  def push(event, payload), do:
    send(__MODULE__, {:push, event, payload})

  # ...
end
```

And now you can invoke `YourSocket.push(event, payload)` from an arbitrary process.

So in my opinion, the proposed `push/3` doesn't really solve a complex problem.

One final issue I have with supporting push is that in your proposal, `push/3` is an "outside" push (from an external process), while `push/4` is an inside push (from within the behaviour process). This seems confusing, so we'd need a better naming distinction.

For all these reasons, I think that `push/3` in the proposed form adds more problems than it solves.

All that being said, one thing which is indeed missing is the support for synchronous calls (`GenSocketClient.call`), which would allow you to implement sync pushes. Currently, it's not obvious how to do that, so I'll see about supporting that scenario.

**Comment by sasa1977** [comment]
Just an addendum, that we've pushed `1.1.0` to hex. The new version supports [call](https://hexdocs.pm/phoenix_gen_socket_client/1.1.0/Phoenix.Channels.GenSocketClient.html#call/3),  so you can now easily implement an ack-ed push as:

```elixir
defmodule YourSocket do
  @behaviour GenSocketClient

  def start_link(...), do:
    GenSocketClient.start_link(..., name: __MODULE__)

  def push(topic, event, payload), do:
    GenSocketClient.call(__MODULE__, {:push, topic, event, payload})

  def handle_call({:push, topic, event, payload}, _from, state) do
    res = GenSocketClient.push(transport, topic, event, payload)
    {:reply, res, state}
  end
end
```

**Comment by gregwoodward** [comment]
great!  thank you very much for the info about handle_call(); we'll definitely switch out our code to use the approach you've suggested. Thank you for taking the time to consider our request, and for suggesting a better alternative.  :)

**Comment by sasa1977** [comment]
No problem. Let us know if this doesn't work for you.

**Comment by ericTsiliacos** [comment]
@sasa1977 in the addendum, inside handle_call, there is reference to a `transport`, do you have any idea where it might come from/ get stored? thank you!

**Comment by ericTsiliacos** [comment]
@sasa1977 Thanks again! It worked. We had to change the parameters a bit. The example code in your addendum mentioned a `transport`. Looking at the docs, the 3rd argument to `handle_call/4` provides it.

So, `handle_call` should be this
```elixir
def handle_call({:push, topic, event, payload}, _from, transport, state) do
  res = GenSocketClient.push(transport, topic, event, payload)
  {:reply, res, state}
end
```

**Comment by sasa1977** [comment]
Ah, sorry about that, I was live-coding in GH, without trying it out :-)

**Pull request closed without merging**
